"""Type stubs for lxml."""

from __future__ import annotations

from typing import Any, Iterator

class _Element:
    tag: str
    text: str | None
    tail: str | None
    attrib: dict[str, str]

    def get(self, key: str, default: str | None = None) -> str | None: ...
    def set(self, key: str, value: str) -> None: ...
    def find(self, path: str, namespaces: dict[str, str] | None = None) -> _Element | None: ...
    def findall(self, path: str, namespaces: dict[str, str] | None = None) -> list[_Element]: ...
    def findtext(self, path: str, default: str | None = None, namespaces: dict[str, str] | None = None) -> str | None: ...
    def xpath(self, path: str, namespaces: dict[str, str] | None = None) -> list[_Element]: ...
    def iter(self, tag: str | None = None) -> Iterator[_Element]: ...
    def itertext(self) -> Iterator[str]: ...
    def append(self, element: _Element) -> None: ...
    def insert(self, index: int, element: _Element) -> None: ...
    def remove(self, element: _Element) -> None: ...
    def clear(self) -> None: ...
    def __iter__(self) -> Iterator[_Element]: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> _Element: ...

class _ElementTree:
    def __init__(self, element: _Element | None = None) -> None: ...
    def getroot(self) -> _Element: ...
    def write(self, file: Any, **kwargs: Any) -> None: ...
    def iter(self, tag: str | None = None) -> Iterator[_Element]: ...

class XMLParser:
    def __init__(
        self,
        remove_blank_text: bool = False,
        remove_comments: bool = False,
        huge_tree: bool = False,
        resolve_entities: bool = True,
    ) -> None: ...

class XMLSyntaxError(Exception):
    pass

class XPathEvalError(Exception):
    pass

def Element(tag: str, attrib: dict[str, str] | None = None, **extra: str) -> _Element: ...
def SubElement(parent: _Element, tag: str, attrib: dict[str, str] | None = None, **extra: str) -> _Element: ...
def tostring(element: _Element, encoding: str | None = None, method: str = "xml", **kwargs: Any) -> bytes: ...
def fromstring(text: str | bytes, parser: XMLParser | None = None) -> _Element: ...
def parse(source: Any, parser: XMLParser | None = None) -> _ElementTree: ...

def ElementTree(element: _Element | None = None) -> _ElementTree: ...

class etree:
    Element = Element
    SubElement = SubElement
    tostring = tostring
    fromstring = fromstring
    parse = parse
    ElementTree = ElementTree
    XMLParser = XMLParser
    XMLSyntaxError = XMLSyntaxError
    XPathEvalError = XPathEvalError
    _Element = _Element
    _ElementTree = _ElementTree
