"""Type stubs for Sublime Text API."""

from typing import Any, Callable, Optional, List

Point = int
Value = bool | str | int | float | list | dict | None
CommandArgs = Optional[dict[str, Value]]

class Settings:
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Value) -> None: ...
    def has(self, key: str) -> bool: ...
    def erase(self, key: str) -> None: ...
    def add_on_change(self, key: str, callback: Callable[[], None]) -> None: ...
    def clear_on_change(self, key: str) -> None: ...

class Region:
    def __init__(self, a: int, b: int = ...) -> None: ...
    a: int
    b: int
    xpos: float
    def empty(self) -> bool: ...
    def begin(self) -> Point: ...
    def end(self) -> Point: ...
    def size(self) -> int: ...
    def contains(self, x: Point | Region) -> bool: ...
    def intersects(self, region: Region) -> bool: ...
    def intersection(self, region: Region) -> Region: ...
    def cover(self, region: Region) -> Region: ...

class Selection:
    def __iter__(self) -> Any: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Region: ...
    def clear(self) -> None: ...
    def add(self, region: Region) -> None: ...
    def add_all(self, regions: List[Region]) -> None: ...
    def subtract(self, region: Region) -> None: ...
    def contains(self, region: Region) -> bool: ...

class View:
    def id(self) -> int: ...
    def buffer_id(self) -> int: ...
    def file_name(self) -> Optional[str]: ...
    def is_valid(self) -> bool: ...
    def is_loading(self) -> bool: ...
    def size(self) -> int: ...
    def substr(self, region: Region | Point) -> str: ...
    def text(self) -> str: ...
    def scope_name(self, point: Point) -> str: ...
    def match_selector(self, pt: Point, selector: str) -> bool: ...
    def sel(self) -> Selection: ...
    def line(self, point: Point | Region) -> Region: ...
    def word(self, point: Point | Region) -> Region: ...
    def find(self, pattern: str, start_pt: Point = 0, flags: int = 0) -> Region: ...
    def find_all(self, pattern: str, flags: int = 0, fmt: Optional[str] = None) -> List[Region]: ...
    def settings(self) -> Settings: ...
    def close(self) -> None: ...
    def window(self) -> Optional[Window]: ...
    def show(self, region: Region | Point, show_surrounds: bool = True, keep_to_left: bool = False, animate: bool = True) -> None: ...
    def insert(self, edit: Any, point: Point, text: str) -> int: ...
    def erase(self, edit: Any, region: Region) -> None: ...
    def replace(self, edit: Any, region: Region, text: str) -> None: ...
    def expand_by_class(self, point: Point, classes: int, separators: str = '') -> Region: ...
    def add_regions(self, key: str, regions: List[Region], scope: str = '', icon: str = '', flags: int = 0) -> None: ...
    def get_regions(self, key: str) -> List[Region]: ...
    def erase_regions(self, key: str) -> None: ...
    def run_command(self, cmd: str, args: CommandArgs = None) -> None: ...
    def erase_status(self, key: str) -> None: ...
    def text_point(self, row: int, col: int) -> Point: ...
    def show_at_center(self, region: Region | Point, animate: bool = True) -> None: ...
    def show_popup(self, content: str, flags: int = 0, location: int = -1, max_width: int = 320, max_height: int = 240, on_navigate: Optional[Callable[[str], None]] = None, on_hide: Optional[Callable[[], None]] = None) -> None: ...
    def hide_popup(self) -> None: ...
    def assign_syntax(self, syntax: str) -> None: ...
    def rowcol(self, point: Point) -> tuple[int, int]: ...
    def extract_variables(self) -> dict[str, str]: ...

class Sheet:
    def id(self) -> int: ...
    def window(self) -> Optional[Window]: ...
    def view(self) -> Optional[View]: ...

class Window:
    def id(self) -> int: ...
    def is_valid(self) -> bool: ...
    def active_sheet(self) -> Optional[Sheet]: ...
    def active_view(self) -> Optional[View]: ...
    def sheets(self) -> List[Sheet]: ...
    def views(self, include_transient: bool = False) -> List[View]: ...
    def selected_sheets(self) -> List[Sheet]: ...
    def new_file(self, flags: int = 0, syntax: str = '') -> View: ...
    def open_file(self, fname: str, flags: int = 0, group: int = -1) -> View: ...
    def find_open_file(self, fname: str, group: int = -1) -> Optional[View]: ...
    def file_history(self) -> List[str]: ...
    def create_output_panel(self, name: str, unlisted: bool = False) -> View: ...
    def find_output_panel(self, name: str) -> Optional[View]: ...
    def destroy_output_panel(self, name: str) -> None: ...
    def show_input_panel(
        self,
        caption: str,
        initial_text: str,
        on_done: Callable[[str], None],
        on_change: Optional[Callable[[str], None]],
        on_cancel: Optional[Callable[[], None]]
    ) -> View: ...
    def show_quick_panel(
        self,
        items: List[Any],
        on_select: Callable[[int], None],
        flags: int = 0,
        selected_index: int = -1,
        on_highlight: Optional[Callable[[int], None]] = None,
        placeholder: Optional[str] = None
    ) -> None: ...
    def project_file_name(self) -> Optional[str]: ...
    def project_data(self) -> Value: ...
    def set_project_data(self, data: Value) -> None: ...
    def settings(self) -> Settings: ...
    def folders(self) -> List[str]: ...
    def extract_variables(self) -> dict[str, str]: ...
    def status_message(self, text: str) -> None: ...
    def is_sidebar_visible(self) -> bool: ...
    def set_sidebar_visible(self, flag: bool, animate: bool = True) -> None: ...
    def focus_view(self, view: View) -> None: ...
    def run_command(self, cmd: str, args: CommandArgs = None) -> None: ...

class Phantom:
    def __init__(self, region: Region, content: str, layout: int, on_navigate: Optional[Callable[[str], None]] = None) -> None: ...

class PhantomSet:
    def __init__(self, view: View, key: str = '') -> None: ...
    def update(self, phantoms: List[Phantom]) -> None: ...

def version() -> str: ...
def platform() -> str: ...
def arch() -> str: ...
def channel() -> str: ...
def executable_path() -> str: ...
def packages_path() -> str: ...
def status_message(msg: str) -> None: ...
def error_message(msg: str) -> None: ...
def message_dialog(msg: str) -> None: ...
def ok_cancel_dialog(msg: str, ok_title: str = '', title: str = '') -> bool: ...
def run_command(cmd: str, args: CommandArgs = None) -> None: ...
def get_clipboard(size_limit: int = 16777216) -> str: ...
def set_clipboard(text: str) -> None: ...
def load_settings(base_name: str) -> Settings: ...
def save_settings(base_name: str) -> None: ...
def load_resource(name: str) -> str: ...
def load_binary_resource(name: str) -> bytes: ...
def find_resources(pattern: str) -> List[str]: ...
def encode_value(value: Value, pretty: bool = False) -> str: ...
def decode_value(data: str) -> Value: ...
def set_timeout(callback: Callable[..., Any], delay: int = 0) -> None: ...
def set_timeout_async(callback: Callable[..., Any], delay: int = 0) -> None: ...
def active_window() -> Window: ...
def windows() -> List[Window]: ...
def log_commands(flag: bool) -> None: ...

ENCODED_POSITION: int
TRANSIENT: int
FORCE_GROUP: int
COOPERATE_WITH_AUTO_COMPLETE: int
HIDE_ON_MOUSE_MOVE_AWAY: int
LAYOUT_INLINE: int
LAYOUT_BELOW: int
LAYOUT_BLOCK: int
CLASS_WORD_START: int
CLASS_WORD_END: int
CLASS_PUNCTUATION_START: int
CLASS_PUNCTUATION_END: int
CLASS_SUB_WORD_START: int
CLASS_SUB_WORD_END: int
CLASS_LINE_START: int
CLASS_LINE_END: int
CLASS_EMPTY_LINE: int
